### ISSUE TITLE
Set different themes for workspaces

### ISSUE THREAD

**Issue by szutsattila** [mallowigi/mtslack#60]
**Describe the solution you'd like**
It would be great if we could set different themes for different workspaces. So for example for workspace one material ocean and for workspace two solarized dark. And when we switch between workspaces the themes load automatically.

**Describe alternatives you've considered**
You can always change manually when you switch workspaces but it would be nice if it loaded automatically, and saved the previously loaded theme as default.

**Additional context**

**Comment by mallowigi** [comment]
Good idea! I'll try to implement that once I'm done with my backlog of other projects

**Comment by mallowigi** [comment]
done!

**Comment by szutsattila** [comment]
Thank you! However, this broke my installation of slack-desktop. I am on Ubuntu 20.04, Gnome. Let me know what other information you need. 

It removes all my workspaces, except the last. Sometimes it didn't even launch. Removing the extension doesn't solve it either, I still can't access my workspaces, the whole workspaces sidebar disappeared. Keyboard shortcuts don't work. (Ctrl+1, ctrl+q, etc.). I had to purge and reinstall slack to revert back.

**Comment by mallowigi** [comment]
Maybe it has something to do with the executable, I'll install a Linux env and check when I have the time
